site_name: MediaNest
repo_url: https://github.com/medianest/website
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2023 MediaNest
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
theme:
  name: material
  language: en 
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github 
  font:
    text: Inter
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - toc.integrate 
    - navigation.top
    - search
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MyMediaNest
      name: MyMediaNest on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/MediaNest
      name: MediaNest on GitHub
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/medianest
      name: MediaNest on Docker
    # - icon: fontawesome/brands/facebook
    #   link: https://facebook.com/MyMediaNest
    #   name: MyMediaNest on Facebook
    # - icon: fontawesome/brands/instagram
    #   link: https://instagram.com/MyMediaNest
    #   name: MyMediaNest on Instagram
    - icon: fontawesome/brands/discord
      link: https://discord.gg/9exADz8Zp6
      name: Join the MediaNest Discord
    # - icon: fontawesome/brands/reddit
    #   link: https://reddit.com/r/MyMediaNest
    #   name: MyMediaNest on Reddit
    # - icon: fontawesome/brands/youtube
    #   link: https://youtube.com/@MyMediaNest
    #   name: MyMediaNest on YouTube
    # - icon: fontawesome/brands/twitch
    #   link: https://twitch.tv/MyMediaNest
    #   name: MyMediaNest on Twitch
  analytics:
    provider: google
    property: G-7Z4YJ189SP
  generator: false
  feedback:
    title: Was this page helpful?
    ratings:
      - icon: material/emoticon-happy-outline
        name: This page was helpful
        data: 1
        note: >-
          Thanks for your feedback!
      - icon: material/emoticon-sad-outline
        name: This page could be improved
        data: 0
        note: >- 
          Thanks for your feedback!
